### ISSUE TITLE
Please I need help with this error

### ISSUE THREAD

**Issue by talented-vicky** [nodemailer/nodemailer-sendgrid#16]
ResponseError: Unauthorized
    at Request._callback (C:\Users\HP\Documents\personal\node_js\shopping\shopping-app\node_modules\@sendgrid\client\src\classes\client.js:124:25)
    at Request.self.callback (C:\Users\HP\Documents\personal\node_js\shopping\shopping-app\node_modules\request\request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (C:\Users\HP\Documents\personal\node_js\shopping\shopping-app\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (C:\Users\HP\Documents\personal\node_js\shopping\shopping-app\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 401,
  response: {
    headers: {
      server: 'nginx',
      date: 'Wed, 18 Jan 2023 23:59:51 GMT',
      'content-type': 'application/json',
      'content-length': '116',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html',        
      'strict-transport-security': 'max-age=600; includeSubDomains'
    },
    body: { errors: [Array] }
  }
}

**Comment by talented-vicky** [comment]
I have printed the api_key in my terminal and it's actually the same as what I have in my sendGrid account

**Comment by TylerThompson** [comment]
@talented-vicky not from sendgrid or nodemailer, but this could be a permissions issue with the apikey user
